### ISSUE TITLE
[BUG] package provides `ext-json`

### ISSUE THREAD

**Issue by jkowalleck** [abdFal/Tax-Calculation#1]
Hi @abdFal,

I found your work, because it listed on composer's public package registry as the only package that provides `ext-json`.

see <https://packagist.org/packages/abdfal/my-php-library>
see https://github.com/abdFal/Tax-Calculation/blob/8e8611ef71a1a8a4260f144ed129564430cd1085/composer.json#L18-L20

This is a mistake, right?

Could you remove this capability from your package and push an update to packagist.org so your package gets delisted from this feature `ext-json`.

**Comment by abdFal** [comment]
Thank you @jkowalleck for your issue and solution!
